# Generated by Django 5.2.7 on 2025-11-24 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Дата')),
                ('total_visitors', models.IntegerField(default=0, verbose_name='Всего посетителей')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='Уникальные посетители')),
                ('new_visitors', models.IntegerField(default=0, verbose_name='Новые посетители')),
                ('returning_visitors', models.IntegerField(default=0, verbose_name='Возвращающиеся посетители')),
                ('total_pageviews', models.IntegerField(default=0, verbose_name='Всего просмотров страниц')),
                ('avg_pages_per_visitor', models.FloatField(default=0, verbose_name='Среднее страниц на посетителя')),
                ('avg_time_on_site', models.FloatField(default=0, verbose_name='Среднее время на сайте (мин)')),
                ('bounce_rate', models.FloatField(default=0, verbose_name='Показатель отказов (%)')),
                ('news_published', models.IntegerField(default=0, verbose_name='Опубликовано новостей')),
                ('grants_published', models.IntegerField(default=0, verbose_name='Опубликовано грантов')),
                ('scholarships_published', models.IntegerField(default=0, verbose_name='Опубликовано стипендий')),
                ('competitions_published', models.IntegerField(default=0, verbose_name='Опубликовано конкурсов')),
                ('innovations_published', models.IntegerField(default=0, verbose_name='Опубликовано инноваций')),
                ('internships_published', models.IntegerField(default=0, verbose_name='Опубликовано стажировок')),
                ('jobs_published', models.IntegerField(default=0, verbose_name='Опубликовано вакансий')),
                ('mobile_visitors', models.IntegerField(default=0, verbose_name='Мобильные посетители')),
                ('tablet_visitors', models.IntegerField(default=0, verbose_name='Планшетные посетители')),
                ('desktop_visitors', models.IntegerField(default=0, verbose_name='Десктопные посетители')),
            ],
            options={
                'verbose_name': 'Ежедневная статистика',
                'verbose_name_plural': 'Ежедневная статистика',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ сессии')),
                ('first_visit', models.DateTimeField(auto_now_add=True, verbose_name='Первое посещение')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='Последнее посещение')),
                ('visit_count', models.IntegerField(default=1, verbose_name='Количество визитов')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('browser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Браузер')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОС')),
                ('device', models.CharField(choices=[('mobile', 'Мобильный'), ('tablet', 'Планшет'), ('desktop', 'Десктоп')], default='desktop', max_length=50, verbose_name='Устройство')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
                'ordering': ['-last_visit'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('path', models.CharField(max_length=500, verbose_name='Путь')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='HTTP метод')),
                ('status_code', models.IntegerField(default=200, verbose_name='Статус код')),
                ('referer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Источник перехода')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время просмотра')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('time_spent', models.IntegerField(blank=True, null=True, verbose_name='Время на странице (сек)')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип контента')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.visitor', verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Просмотр страницы',
                'verbose_name_plural': 'Просмотры страниц',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='Уникальные посетители')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Лайки')),
                ('shares_count', models.IntegerField(default=0, verbose_name='Поделились')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
            ],
            options={
                'verbose_name': 'Статистика контента',
                'verbose_name_plural': 'Статистика контента',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'content_type'], name='analytics_c_date_41c95c_idx')],
                'unique_together': {('content_type', 'object_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('view', 'Просмотр'), ('login', 'Вход'), ('logout', 'Выход')], max_length=50, verbose_name='Действие')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип контента')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность пользователя',
                'verbose_name_plural': 'Активность пользователей',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='analytics_u_user_id_54ee7d_idx'), models.Index(fields=['action', 'timestamp'], name='analytics_u_action_2b16c2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['ip_address', 'session_key'], name='analytics_v_ip_addr_4bacac_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['last_visit'], name='analytics_v_last_vi_c62641_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['timestamp', 'path'], name='analytics_p_timesta_cd14c8_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['content_type', 'object_id'], name='analytics_p_content_73920a_idx'),
        ),
    ]
