services:
  db:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: youth_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty1514
    ports:
      - "0.0.0.0:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - my_network

  web:
    build: .
    container_name: django_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - HOST=db
      - POSTGRES_DB=youth_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty1514
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - SECRET_KEY=2m)nb^qin_cohksys)nvvuo@+@0f#rs9@@yxfsugi9!e!6@%*k
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:3000,http://127.0.0.1:5173,http://127.0.0.1:5174,http://127.0.0.1:5175,http://127.0.0.1:5176
      - CSRF_TRUSTED_ORIGINS=http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:3000
    networks:
      - my_network
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    container_name: django_ngrok
    depends_on:
      - web
    environment:
      - NGROK_AUTHTOKEN=373ujIpNeSorWddIOcBMZyjMbwx_7aJapwY8E7ud3vdJJ2W1p
    # Используем случайный URL без фиксированного домена
    # Добавляем --log=stdout чтобы видеть логи
    command: http web:8000 --log=stdout
    networks:
      - my_network
    restart: "no"

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
