# Generated by Django 5.2.7 on 2025-10-15 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_remove_organisation_department_and_more'),
        ('users', '0002_remove_user_confirmation_code_remove_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation'),
        ),
    ]
