# Generated by Django 5.2.7 on 2025-11-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_confirmation_code_remove_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_menus',
            field=models.JSONField(blank=True, default=list, help_text='Список разрешенных меню для администратора'),
        ),
    ]
