# Generated by Django 4.2.17 on 2025-12-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_organization_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Администратор'), ('Moderator', 'Модератор'), ('Coordinator', 'Координатор'), ('User', 'Пользователь')], default='User', max_length=255),
        ),
    ]
