# Generated by Django 4.2.17 on 2025-12-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_coordinator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, choices=[('secondary', 'Среднее образование'), ('higher', 'Высшее образование')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_cefr',
            field=models.BooleanField(default=False, verbose_name='Имеет CEFR'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_ielts',
            field=models.BooleanField(default=False, verbose_name='Имеет IELTS'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_topik',
            field=models.BooleanField(default=False, verbose_name='Имеет TOPIK'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_foreign_graduate',
            field=models.BooleanField(default=False, verbose_name='Выпускник зарубежного вуза'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_promoted',
            field=models.BooleanField(default=False, verbose_name='Повышен в должности'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_top300_graduate',
            field=models.BooleanField(default=False, verbose_name='Выпускник TOP 300'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_top500_graduate',
            field=models.BooleanField(default=False, verbose_name='Выпускник TOP 500'),
        ),
        migrations.AddField(
            model_name='user',
            name='leadership_position',
            field=models.CharField(blank=True, choices=[('director', 'Директор'), ('head', 'Начальник'), ('manager', 'Менеджер')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='scientific_degree',
            field=models.CharField(blank=True, choices=[('phd', 'PhD'), ('dsc', 'DSc'), ('candidate', 'Соискатель')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('technical', 'Технический сотрудник'), ('service', 'Обслуживающий персонал')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state_award_type',
            field=models.CharField(blank=True, choices=[('order', 'Орден'), ('medal', 'Медаль'), ('honorary', 'Почетное звание')], max_length=50, null=True),
        ),
    ]
