# Generated by Django 5.2.7 on 2025-11-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grants/', verbose_name='Изображение'),
        ),
    ]
