# Generated by Django 5.2.7 on 2025-11-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scholarships/', verbose_name='Изображение'),
        ),
    ]
