# Generated by Django 5.2.7 on 2025-11-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_scholarship_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='competitions/', verbose_name='Изображение'),
        ),
    ]
