# Generated by Django 5.2.7 on 2025-11-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_competition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='innovations/', verbose_name='Изображение'),
        ),
    ]
