# Generated by Django 5.2.7 on 2025-11-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_innovation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='internships/', verbose_name='Изображение'),
        ),
    ]
