# Generated by Django 5.2.7 on 2025-12-16 08:35

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_internship_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title_uz', models.CharField(max_length=500, verbose_name='Sarlavha (UZ)')),
                ('title_ru', models.CharField(max_length=500, verbose_name='Sarlavha (RU)')),
                ('title_en', models.CharField(max_length=500, verbose_name='Sarlavha (EN)')),
                ('abstract_uz', models.TextField(verbose_name='Annotatsiya (UZ)')),
                ('abstract_ru', models.TextField(verbose_name='Annotatsiya (RU)')),
                ('abstract_en', models.TextField(verbose_name='Annotatsiya (EN)')),
                ('content_uz', ckeditor.fields.RichTextField(verbose_name="To'liq matn (UZ)")),
                ('content_ru', ckeditor.fields.RichTextField(verbose_name="To'liq matn (RU)")),
                ('content_en', ckeditor.fields.RichTextField(verbose_name="To'liq matn (EN)")),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='articles/pdfs/', verbose_name='PDF fayl')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/', verbose_name='Muqova rasmi')),
                ('category', models.CharField(choices=[('international', 'Xalqaro'), ('local', 'Mahalliy'), ('scientific', 'Ilmiy'), ('analytical', 'Tahliliy'), ('practical', 'Amaliy')], max_length=50, verbose_name='Kategoriya')),
                ('keywords_uz', models.CharField(blank=True, max_length=500, verbose_name="Kalit so'zlar (UZ)")),
                ('keywords_ru', models.CharField(blank=True, max_length=500, verbose_name="Kalit so'zlar (RU)")),
                ('keywords_en', models.CharField(blank=True, max_length=500, verbose_name="Kalit so'zlar (EN)")),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Nashr sanasi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('revision', "Qayta ko'rib chiqish")], default='pending', max_length=20, verbose_name='Holati')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar")),
                ('downloads', models.IntegerField(default=0, verbose_name='Yuklab olishlar')),
                ('likes', models.IntegerField(default=0, verbose_name='Yoqishlar')),
                ('is_published', models.BooleanField(default=False, verbose_name='Nashr qilingan')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tanlangan')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_articles', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'db_table': 'content_articles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_published'], name='content_art_status_0d45e4_idx'), models.Index(fields=['category', 'status'], name='content_art_categor_8c850c_idx'), models.Index(fields=['author', 'status'], name='content_art_author__2e7c9a_idx'), models.Index(fields=['-created_at'], name='content_art_created_0d6cbf_idx')],
            },
        ),
    ]
