# Generated by Django 5.2.7 on 2025-12-19 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_appeal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appeal',
            new_name='content_app_status_c5f161_idx',
            old_name='content_app_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appeal',
            new_name='content_app_user_id_45f814_idx',
            old_name='content_app_user_idx',
        ),
        migrations.RenameIndex(
            model_name='appeal',
            new_name='content_app_is_anon_fab7eb_idx',
            old_name='content_app_is_anon_idx',
        ),
        migrations.RenameIndex(
            model_name='youthstatisticshistory',
            new_name='youth_stati_recorde_403855_idx',
            old_name='youth_stati_recorde_idx',
        ),
        migrations.RenameIndex(
            model_name='youthstatisticshistory',
            new_name='youth_stati_statist_5223aa_idx',
            old_name='youth_stati_statist_idx',
        ),
        migrations.AddField(
            model_name='appeal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appeal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
