# Generated by Django 5.2.7 on 2025-10-15 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='department',
        ),
        migrations.AlterField(
            model_name='section',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='organisation.department'),
        ),
    ]
