# Generated by Django 5.2.7 on 2025-10-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_remove_organisation_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_uz',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
