# Generated by Django 5.2.7 on 2025-10-27 11:27

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_department_name_en_department_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name': 'CategoryNew',
                'verbose_name_plural': 'Yangiliklar kategoyasi',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Sarlavha')),
                ('mainImage', models.ImageField(blank=True, default='new.png', null=True, upload_to='', verbose_name='Asosiy rasm. 500x500 shart')),
                ('description_1', models.TextField(blank=True, null=True, verbose_name="Ta'rif 1")),
                ('description_2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Ta'rif 2")),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 1')),
                ('description_3', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Ta'rif 3")),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 2')),
                ('description_4', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Ta'rif 4")),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 3')),
                ('description_5', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Ta'rif 5")),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 4')),
                ('img_5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 5')),
                ('date', models.DateField()),
                ('view', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new', to='organisation.categorynew', verbose_name='Kategoriyani tanlang')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
